- intercom/package.json
- intercom/src/App.js
- intercom/src/App.test.js
- intercom/src/components/Team/Team.js
- intercom/src/components/Team/Team.spec.js
- intercom/src/host.js
- intercom/src/index.js
- intercom/yarn.lock
https://trello.com/c/JuGwjY7u/44-fe-modify-the-fe-to-pull-and-display-team-members-names-from-be
> Team Mems - Component Renders and pulls from BE

- intercom/package.json
- intercom/public/index.html
- intercom/src/App.js
- intercom/src/Auth/Auth.js
- intercom/src/Auth/Authenticating.js
- intercom/src/components/Intro/Intro.js
- intercom/src/components/Users/SingleUser.js
- intercom/src/history.js
- intercom/src/index.js
- intercom/src/routes.js
- intercom/yarn.lock
https://trello.com/c/ztHs2JLS/58-implement-auth0-in-fe
> Auth0 Initial Implementation

- intercom/.gitignore
- intercom/package.json
- intercom/src/Auth/Auth.js
- intercom/src/Auth/authVars.js
- intercom/yarn.lock
https://trello.com/c/PbTyZJQD/63-config-auth0-environmental-variables-for-both-local-development-and-deployment
> auth0-config-env-vars

- intercom/src/Auth/Auth.js
https://trello.com/b/X5DhzRqC/labs-11-intercom-app
> Hard coded production callback url for deployment.

- intercom/src/Auth/Auth.js
Reverts intercom-app/labs11-IntercomApp-FE#9
> Revert "Hard coded production callback url for deployment."

- intercom/src/App.js
- intercom/src/Auth/Auth.js
- intercom/src/components/Intro/Intro.js
- intercom/src/components/Users/SingleUser.js
renewSession removed from App.js so singleUser page displayed
> Auth0 on FE

- intercom/src/components/Groups/GroupForm.js
- intercom/src/components/Groups/GroupsBelonged.js
- intercom/src/components/Groups/GroupsInvited.js
- intercom/src/components/User/User.js
Group information displayed in single user page.
> Users group

- intercom/src/components/GroupChatroom/GroupChatroomView.js
https://trello.com/c/TzjmQHL6/113-chatroom-view-add-delete-leave-group-buttons
> Chatroom view

- intercom/src/components/GroupChatroom/GroupChatroomView.js
- intercom/yarn.lock
https://trello.com/c/DEJN6Wol/116-chatroom-view-add-update-group-option-for-owners
> Chatroom View - Added update group form for group name change.

- intercom/src/components/AccountSettings/AccountSettings.js
https://trello.com/c/f4FzF4ra/122-account-settings-view
> Account view - Delete Account

- intercom/src/components/AccountSettings/AccountSettings.js
- intercom/src/components/AccountSettings/AccountUpdateForm.js
https://trello.com/c/IZVJMfsT/130-account-setting-view-update-account
> Account View - Update Display Name

- intercom/package.json
- intercom/src/App.js
- intercom/src/components/GroupChatroom/GroupChatroomView.js
- intercom/src/components/GroupMembers/GroupMembersView.js
- intercom/src/components/Search/SearchBar.js
- intercom/src/components/Search/SearchResults.js
- intercom/yarn.lock
https://trello.com/c/NMfFaG4o/121-group-members-search-invite
> Search User - Invite Users

- intercom/src/components/GroupMembers/GroupInviteesList.js
- intercom/src/components/GroupMembers/GroupMembersList.js
- intercom/src/components/GroupMembers/GroupMembersView.js
- intercom/src/components/Navigation/Navigation.js
- intercom/src/components/Search/SearchBar.js
https://trello.com/c/Xp7u3TZF/139-group-members-view-for-owners-only
> Members View - Owner Only 

- intercom/src/components/GroupChatroom/GroupChatroomCall.js
- intercom/src/components/GroupMembers/GroupInviteesList.js
- intercom/src/components/GroupMembers/GroupMembersList.js
- intercom/src/components/GroupMembers/GroupMembersView.js
- intercom/src/components/Navigation/Navigation.js
- intercom/src/components/Search/SearchBar.js
Chatroom View: Handle Call Button if user on call with another group
> Chatroom Call Button

- intercom/public/index.html
- intercom/src/components/Groups/GroupForm.js
- intercom/src/components/Groups/GroupsBelonged.js
- intercom/src/components/Groups/GroupsInvited.js
- intercom/src/components/Groups/GroupsOwned.js
- intercom/src/components/Navigation/Navigation.js
- intercom/src/components/User/User.js
https://trello.com/c/BMd5vAeh/148-initial-styling-of-groups-owned-belonged-invited
> Initial Styling Of Groups and Create Group Form on Users View

- intercom/public/index.html
- intercom/src/components/GroupMembers/GroupInviteesList.js
- intercom/src/components/GroupMembers/GroupMembersList.js
- intercom/src/components/GroupMembers/GroupMembersView.js
- intercom/src/components/Groups/GroupForm.js
- intercom/src/components/Groups/GroupsBelonged.js
- intercom/src/components/Groups/GroupsInvited.js
- intercom/src/components/Groups/GroupsOwned.js
- intercom/src/components/Navigation/Navigation.js
- intercom/src/components/Search/SearchBar.js
- intercom/src/components/Search/SearchResults.js
- intercom/src/components/User/User.js
https://trello.com/c/oqEvmWDF/149-members-view-initial-styling
> Members View - Initial Styling of view with html templates

- intercom/public/index.html
- intercom/src/components/AccountSettings/AccountSettings.js
- intercom/src/components/AccountSettings/AccountUpdateForm.js
- intercom/src/components/GroupMembers/GroupInviteesList.js
- intercom/src/components/GroupMembers/GroupMembersList.js
- intercom/src/components/GroupMembers/GroupMembersView.js
- intercom/src/components/Groups/GroupForm.js
- intercom/src/components/Groups/GroupsBelonged.js
- intercom/src/components/Groups/GroupsInvited.js
- intercom/src/components/Groups/GroupsOwned.js
- intercom/src/components/Navigation/Navigation.js
- intercom/src/components/Search/SearchBar.js
- intercom/src/components/Search/SearchResults.js
- intercom/src/components/User/User.js
https://trello.com/c/YiYN6GfM/150-account-view-initial-styling
> Initial Styling of Accounts View with html template

- intercom/src/components/PricingAndPurchasing/AddToAccountBalance.js
Breaking up functions that create and attache sources (i.e. payment methods) to customers.
> Debugging and testing creating stripe customers sources and charges

- intercom/public/css/patros.css
- intercom/public/index.html
- intercom/src/components/LandingPage/Contact.js
- intercom/src/components/LandingPage/Footer.js
- intercom/src/components/LandingPage/LandingPageView.js
- intercom/src/components/LandingPage/Services.js
- intercom/src/components/LandingPage/SignUp.js
- intercom/src/components/Navigation/Navigation.js
https://trello.com/c/fuBBv2GH/180-contact-form-submit-not-functioning-on-landing-page
https://trello.com/c/gqbgWBY3/184-sign-up-section-on-landing-page
> Landing Page - Contact and Sign Up Component

- intercom/src/components/Groups/GroupForm.js
- intercom/src/components/User/User.js
https://trello.com/c/PBLqDj5e/171-invite-needs-to-clear-state-upon-creating-new-groups-many-times
> Bug Fix - Create Group Form

- intercom/src/components/AccountSettings/AccountSettings.js
- intercom/src/components/AccountSettings/DeleteAccount.js
Account deletion modal now appears when you click delete account, requires the user to type in their email address to confirm deletion.
> Added modal to confirm account deletion

- intercom/public/css/patros.css
- intercom/src/components/GroupChatroom/GroupChatroomActivities.js
- intercom/src/components/Groups/GroupForm.js
- intercom/src/components/RecentActivity/RecentActivity.js
- intercom/src/components/User/User.js
https://trello.com/c/wckCllTv/188-add-recent-activity-to-user-view
> User Page - Recent Activities

- intercom/public/css/patros.css
- intercom/src/components/Groups/GroupsBelonged.js
- intercom/src/components/Groups/GroupsInvited.js
- intercom/src/components/Groups/GroupsOwned.js
https://trello.com/c/V72xsb0I/194-users-groups-on-main-page-minimize-option
> User View - Styling Groups Minimize

- intercom/src/components/PricingAndPurchasing/AddToAccountBalanceNew.js
- intercom/src/components/PricingAndPurchasing/PricingPurchasingOptions.js
Made new component with a function for charging a customer's saved credit card and adding the charge amount to the user's account balance.
> Charge card and add to account balance functionality 

- intercom/public/css/patros.css
- intercom/src/components/AccountSettings/AccountSettings.js
- intercom/src/components/GroupChatroom/GroupChatroomView.js
- intercom/src/components/GroupMembers/GroupMembersView.js
- intercom/src/components/LandingPage/Contact.js
- intercom/src/components/LandingPage/Services.js
- intercom/src/components/Navigation/Navigation.js
- intercom/src/components/User/User.js
https://trello.com/c/PAdcOuqK/201-auth0-token-logout-when-redirect-to-landing-page
other small fixes such as footer, button rounding, team images, media views, services background color.
> Bugs landing page

- intercom/public/index.html
- intercom/src/components/GroupChatroom/GroupChatroomCall.js
- intercom/src/components/GroupChatroom/GroupChatroomView.js
- intercom/src/components/RecentActivity/RecentActivity.js
https://trello.com/c/vLhdUsO6/193-refactor-chatroom-view-call-buttons-on-web-app-as-call-not-taking-place-on-non-mobile-app
> Chatroom view continue refactor

- intercom/src/components/AccountSettings/AccountSettings.js
- intercom/src/components/Modal/DeleteModal.js
> DeleteModal now appears as a red button, functions on acctSettings

- intercom/src/components/AccountSettings/AccountSettings.js
- intercom/src/components/GroupChatroom/GroupChatroomView.js
- intercom/src/components/Groups/GroupsInvited.js
- intercom/src/components/User/User.js
https://trello.com/c/YGUaGKJf/203-on-delete-account-postgres-trowing-error
> Bug fixes - Delete Account

- intercom/src/components/LandingPage/Team.js
https://trello.com/c/MYzRSM8Y/235-update-landing-page-team-members
> Updated team-members on landing page.

- intercom/src/components/AccountSettings/AccountSettings.js
- intercom/src/components/GroupChatroom/GroupChatroomActivities.js
- intercom/src/components/GroupChatroom/GroupChatroomCall.js
- intercom/src/components/GroupChatroom/GroupChatroomView.js
- intercom/src/components/Groups/CallParticipants.js
- intercom/src/components/Groups/CallStatus.js
- intercom/src/components/Groups/GroupsBelonged.js
- intercom/src/components/Groups/GroupsInvited.js
- intercom/src/components/Groups/GroupsOwned.js
- intercom/src/components/RecentActivity/RecentActivity.js
- intercom/src/components/User/User.js
https://trello.com/c/KQjuoH43/243-refactor-of-users-view-and-chatroom-view
> Refactor users page

- intercom/src/components/AccountSettings/AccountSettings.js
- intercom/src/components/Billing/AddToBalance.js
- intercom/src/components/Billing/AddToBalanceWrapper.js
- intercom/src/components/Billing/UpdateBilling.js
Tested billing endpoints for iOS by using these endpoints on our front-end. Prior to this change, a  lot of the logic for calculating a user's account balance was on the front end. With these new endpoints that logic was moved to the backend in order to simplify front-end logic and make things easier for iOS.
> Testing billing endpoints for ios

- intercom/public/css/intercom.css
- intercom/src/components/AccountSettings/AccountSettings.js
- intercom/src/components/AccountSettings/AccountUpdateForm.js
- intercom/src/components/AccountSettings/DeleteAccount.js
- intercom/src/components/GroupChatroom/GroupChatroomView.js
- intercom/src/components/Groups/GroupForm.js
- intercom/src/components/LandingPage/Home.js
- intercom/src/components/Modal/DeleteModal.js
https://trello.com/c/MWnNfAY9/242-should-we-limit-group-user-name-character-length
> Name limit

- intercom/public/css/intercom.css
- intercom/src/components/AccountSettings/Account.js
- intercom/src/components/AccountSettings/AccountBilling.js
- intercom/src/components/AccountSettings/AccountPlanDetails.js
- intercom/src/components/AccountSettings/AccountProfile.js
- intercom/src/components/AccountSettings/AccountSettings.js
- intercom/src/components/AccountSettings/AccountUpdateForm.js
- intercom/src/components/GroupChatroom/GroupChatroomCall.js
https://trello.com/c/cRHQOd3Y/263-finalize-all-styling-of-account-settings
Still needs styling updates in Billing Component but I don't want to create merge conflicts.
> Styling account settings
